### ISSUE TITLE
`<StatusCode.UNAVAILABLE: (14, 'unavailable')>` failed to connect

### ISSUE THREAD

**Issue by amirothman** [peterwnjenga/reframe#3]
Hi, thanks for the great project. I'm facing an issue when trying to set nnext up. I'm on `Ubuntu 18.04.6 LTS`.

I've run the nnext application via docker:

```
docker run -p 6040:6040 -v/tmp/nnext/data:/data nnext/nnext:latest --data-dir /data
```

The logs are showing:

```
[2022-08-26 11:57:16.194] [warning] Null pointer passed. Initializing.
[2022-08-26 11:57:16.195] [error] RocksDB error: NotFound:
[2022-08-26 11:57:16.195] [info] Loaded 0 indices from disk.
[2022-08-26 11:57:16.205] [info] 🏁 Started NNext at ▸ 127.0.0.1:6040
```

Can I do something about the `RocksDB error` on my machine?

On the Python client, when I try the example:

```
In [36]: nnindex = nnclient.index.create(
    ...:     d=100,
    ...:     name='test_ANN')
```

I get the following exception:

```
Exception: {'code': <StatusCode.UNAVAILABLE: (14, 'unavailable')>, 'message': 'failed to connect to all addresses'}
```

I think something related to docker might be wrongly configured. Let me know if I could push a fix somewhere. Help much appreciated :) 

Thanks in advance! ✌️

**Comment by peter-nnext** [comment]
Hi Amir. Investigating the issue. Thanks for posting.

**Comment by peterwnjenga** [comment]
Hi Amir. The original code related to this repo has been deprecated in favor of a new body of work making it easier to operate on LLM agents.
